-- MySQL Script generated by MySQL Workbench
-- qua 29 nov 2023 14:13:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `ACADEMIA_UEMA` DEFAULT CHARACTER SET utf8 ;
USE `ACADEMIA_UEMA` ;

-- -----------------------------------------------------
-- Table `mydb`.`Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACADEMIA_UEMA`.`Turmas` (
  `idTurmas` INT NOT NULL AUTO_INCREMENT,
  `Nome do Professor` VARCHAR(45) NOT NULL,
  `Horario` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`idTurmas`),
  UNIQUE INDEX `idTurmas_UNIQUE` (`idTurmas` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACADEMIA_UEMA`.`Alunos` (
  `idAlunos` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Discente` TINYINT NOT NULL,
  `Sexo` ENUM('F', 'M', 'NB', 'O') NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(75) NOT NULL,
  `ValordaMensalidade` DECIMAL(5) NOT NULL,
  `IDTurma` INT NOT NULL,
  PRIMARY KEY (`idAlunos`),
  UNIQUE INDEX `idPessoas_UNIQUE` (`idAlunos` ASC) VISIBLE,
  INDEX `fk_Alunos_1_idx` (`IDTurma` ASC) VISIBLE,
  CONSTRAINT `fk_Alunos_1`
    FOREIGN KEY (`IDTurma`)
    REFERENCES `ACADEMIA_UEMA`.`Turmas` (`idTurmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agendamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACADEMIA_UEMA`.`Agendamentos` (
  `idAgendamentos` INT NOT NULL AUTO_INCREMENT,
  `idAlunos` INT NOT NULL,
  `Data` DATE NOT NULL,
  'HORARIO' VARCHAR(7) NOT NULL,
  `TipoAgendamento` ENUM('NUTRICAO', 'AVALIADOR_FISICO') NOT NULL,
  PRIMARY KEY (`idAgendamentos`),
  UNIQUE INDEX `idAlunos_UNIQUE` (`idAlunos` ASC) VISIBLE,
  UNIQUE INDEX `idAgendamentos_UNIQUE` (`idAgendamentos` ASC) VISIBLE,
  CONSTRAINT `alunos_fk`
    FOREIGN KEY (`idAlunos`)
    REFERENCES `ACADEMIA_UEMA`.`Alunos` (`idAlunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Frequencia_Alunos_UEMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACADEMIA_UEMA`.`Frequencia_Alunos_UEMA` (
  `idFrequencia_Alunos_UEMA` INT NOT NULL AUTO_INCREMENT,
  `idAlunos` INT NOT NULL,
  `IDTurma` INT NOT NULL,
  `Data_da_Aula` DATE NOT NULL,
  `Aluno_Faltou` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFrequencia_Alunos_UEMA`),
  UNIQUE INDEX `idFrequencia_Alunos_UEMA_UNIQUE` (`idFrequencia_Alunos_UEMA` ASC) VISIBLE,
  INDEX `fk_Frequencia_Alunos_UEMA_1_idx` (`idAlunos` ASC) VISIBLE,
  CONSTRAINT `fk_Frequencia_Alunos_UEMA_1`
    FOREIGN KEY (`idAlunos`)
    REFERENCES `ACADEMIA_UEMA`.`Alunos` (`idAlunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Frequencia_Alunos_Comunidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACADEMIA_UEMA`.`Frequencia_Alunos_Comunidade` (
  `idFrequencia_Alunos_Comunidade` INT NOT NULL AUTO_INCREMENT,
  `idAlunos` INT NOT NULL,
  `IDTurma` INT NOT NULL,
  `Data_da_Aula` DATE NOT NULL,
  `Aluno_Faltou` ENUM('Sim', 'Não') NOT NULL,
  PRIMARY KEY (`idFrequencia_Alunos_Comunidade`),
  UNIQUE INDEX `idFrequencia_Alunos_Comunidade_UNIQUE` (`idFrequencia_Alunos_Comunidade` ASC) VISIBLE,
  INDEX `fk_Frequencia_Alunos_Comunidade_1_idx` (`idAlunos` ASC) VISIBLE,
  CONSTRAINT `fk_Frequencia_Alunos_Comunidade_1`
    FOREIGN KEY (`idAlunos`)
    REFERENCES `ACADEMIA_UEMA`.`Alunos` (`idAlunos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
